# ---------- DEV MODE ----------
FROM maven:3.9.6-eclipse-temurin-17

WORKDIR /app

# Copiamos el pom para cachear dependencias
COPY pom.xml .
RUN mvn -B dependency:go-offline

# Copiamos el código
COPY . .

# Puerto expuesto
EXPOSE 8080

# Comando para desarrollo
CMD ["mvn", "exec:java"]