com.is1.proyecto.models.Alumno:default
com.is1.proyecto.models.AlumnoExamenFinal:default
com.is1.proyecto.models.AlumnoMateria:default
com.is1.proyecto.models.AlumnoPlanEstudio:default
com.is1.proyecto.models.Carrera:default
com.is1.proyecto.models.Correlatividad:default
com.is1.proyecto.models.Docente:default
com.is1.proyecto.models.DocentePeriodo:default
com.is1.proyecto.models.DocenteResponsableMateria:default
com.is1.proyecto.models.ExamenFinal:default
com.is1.proyecto.models.ExamenFinalMateria:default
com.is1.proyecto.models.Materia:default
com.is1.proyecto.models.MateriaCorrelatividad:default
com.is1.proyecto.models.MateriaPlanEstudio:default
com.is1.proyecto.models.MateriaRelacion:default
com.is1.proyecto.models.Periodo:default
com.is1.proyecto.models.PeriodoMateria:default
com.is1.proyecto.models.Persona:default
com.is1.proyecto.models.PlanEstudio:default
com.is1.proyecto.models.Users:default
